#!/bin/bash
read -p "Please connect to a network, when ready, press enter to continue."
echo "Installing Dependencies..."
sudo apt update && sudo apt install openjfx adb android-tools-fastboot openjdk-11-jdk -y || echo "ERROR: failed to install dependencies!";exit 1

echo "Cloning XiaoMiToolV2..."
git clone https://github.com/francescotescari/XiaoMiToolV2 -b linux || echo "Failed to clone XiaoMiTool!"exit 1
cd XiaoMiToolV2
echo "Building XiaoMi Tool..."
case "$arch" in
 "32") JAVA_HOME=/usr/lib/jvm/java-11-openjdk-armhf ./gradlew build || echo "Failed to build XiaoMiToolV2!" && exit 1 ;;
 "64") JAVA_HOME=/usr/lib/jvm/java-11-openjdk-arm64 ./gradlew build || echo "Failed to build XiaoMiToolV2!" && exit 1 ;;
 *) echo "Failed to detect OS CPU architecture! Something is very wrong." && exit 1 ;;
esac
echo "Creating menu shortcut..."
echo "[Desktop Entry]
Name=XiaoMi Tool
Comment=XiaoMiTool is the all-in-one tool to make modding easy for everyone with a Xiaomi smartphone.
Exec=gksudo -k -u root JAVA_HOME=$JAVA_HOME $HOME/XiaoMiToolV2/gradlew run
Icon=$(dirname "$0")/icon-64.png
Terminal=false
Type=Application
Categories=System" > ~/.local/share/applications/XiaoMiTool.desktop || echo "Failed to create menu shortcut.";exit 1

echo "Creating execution script..."
echo "#!/bin/sh
sudo $HOME/XiaoMiToolV2/gradlew run " | sudo tee /usr/local/bin/xiaomitool >/dev/null
sudo chmod +x /usr/local/bin/xiaomitool || echo "Failed to make execution script executable.";exit 1

echo "Successfully Installed XiaoMiTool!"
exit 0

